### ISSUE TITLE
Error: IndexError: list index out of range

### ISSUE THREAD

**Issue by 0xSpuddy** [tellor-io/monitor#16]
error running monitor.py locally

```
getting makerDAO data from dune analytics
Traceback (most recent call last):
  File "/home/ubuntu/monitor/scripts/monitor.py", line 80, in <module>
    main()
  File "/home/ubuntu/monitor/scripts/monitor.py", line 72, in main
    ds.makerdao_grabdata(init, results, dune_login, DUNE_QUERY_ID)
  File "/home/ubuntu/monitor/scripts/datasource.py", line 156, in makerdao_grabdata
    results.append((times[0], values[0], 1, 'makerDAO'))
IndexError: list index out of range
 
```

**Comment by tallywiesenberg** [comment]
Closed #18
